# Generated by Django 4.2.3 on 2024-02-18 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="deleted",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
