# Generated by Django 4.2.3 on 2024-02-18 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0002_item_created_date_item_deleted"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="deleted",),
        migrations.AddField(
            model_name="item",
            name="deleted_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="created_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="created_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
