# Generated by Django 4.2.3 on 2024-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0003_remove_item_deleted_item_deleted_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
