# Generated by Django 4.2.3 on 2024-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0004_alter_item_deleted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item_images/"),
        ),
    ]
