# Generated by Django 4.2.3 on 2024-03-01 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0007_message_enquiring_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="complete_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="confirm_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
