# Generated by Django 4.2.3 on 2024-03-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0008_rental_complete_date_rental_confirm_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="confirm_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
