# Generated by Django 4.2.3 on 2024-03-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0009_alter_rental_complete_date_alter_rental_confirm_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="cancelled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="pending_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rental",
            name="confirm_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
