# Generated by Django 4.2.3 on 2024-03-30 05:59

from django.db import migrations, models
import irentstuffapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0010_rental_cancelled_date_rental_pending_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                    ("rented", "Rented"),
                ],
                default="active",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="deposit",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_per_day",
            field=irentstuffapp.models.PositiveDecimalField(
                decimal_places=2, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
