# Generated by Django 5.0.4 on 2024-04-04 19:51

import django.core.validators
import irentstuffapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0010_rental_cancelled_date_rental_pending_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Enter a number between 0 and 100 for the discount percentage",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="deposit",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_per_day",
            field=irentstuffapp.models.PositiveDecimalField(
                decimal_places=2, max_digits=10
            ),
        ),
    ]
