# Generated by Django 5.0.1 on 2024-04-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0011_item_discount_percentage_alter_item_deposit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="discount_percentage",
        ),
    ]
