# Generated by Django 5.0.1 on 2024-04-06 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0012_remove_item_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Enter a number between 0 and 100 for the discount percentage",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
