# Generated by Django 5.0.1 on 2024-04-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0013_item_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="apply_loyalty_discount",
            field=models.BooleanField(
                default=False, help_text="Apply loyalty discount for this rental"
            ),
        ),
    ]
