# Generated by Django 5.0.1 on 2024-04-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0011_itemmemento_itemstatescaretaker"),
        ("irentstuffapp", "0014_rental_apply_loyalty_discount"),
    ]

    operations = []
