# Generated by Django 4.2.3 on 2024-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0016_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="deal_confirmed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
