# Generated by Django 4.2.3 on 2024-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0016_interest_userinterests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="min_discount",
        ),
        migrations.AddField(
            model_name="interest",
            name="discount",
            field=models.BooleanField(default=True),
        ),
    ]
