# Generated by Django 4.2.3 on 2024-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0017_purchase_deal_confirmed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("active_rental", "Active Rental"),
                    ("pending_purchase", "Pending Purchase"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="itemmemento",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("active_rental", "Active Rental"),
                    ("pending_purchase", "Pending Purchase"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=255,
            ),
        ),
    ]
