# Generated by Django 4.2.3 on 2024-04-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irentstuffapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irentstuffapp", "0017_remove_interest_min_discount_interest_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("active_rental", "Active Rental"),
                    ("pending_purchase", "Pending Purchase"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="festive_discount_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="festive_discount_percentage",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="festive_discount_price",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="festive_discounts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemmemento",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("active_rental", "Active Rental"),
                    ("pending_purchase", "Pending Purchase"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_date", models.DateField()),
                ("deal_confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("deal_complete_date", models.DateTimeField(blank=True, null=True)),
                ("deal_cancelled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="reserved",
                        max_length=255,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_as_renter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irentstuffapp.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases_as_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
