# Generated by Django 4.2.3 on 2024-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "irentstuffapp",
            "0018_item_availability_item_festive_discount_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="deal_reserved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
