# Generated by Django 4.2.3 on 2024-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0018_item_availability_itemmemento_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="festive_discounts_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
