# Generated by Django 4.2.3 on 2024-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0019_item_festive_discounts_opt_in"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="festive_discounts_opt_in",
            new_name="festive_discounts",
        ),
    ]
