# Generated by Django 4.2.3 on 2024-04-22 15:45

from django.db import migrations
import irentstuffapp.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "irentstuffapp",
            "0020_rename_festive_discounts_opt_in_item_festive_discounts",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="festive_discount_price",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
