# Generated by Django 4.2.3 on 2024-04-24 14:25

from django.db import migrations, models
import irentstuffapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0021_item_festive_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="festive_discount_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="festive_discount_percentage",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="festive_discount_price",
            field=irentstuffapp.models.PositiveDecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
