# Generated by Django 4.2.3 on 2024-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irentstuffapp", "0022_item_festive_discount_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="festive_discount_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
