name: OWASP ZAP Full Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'https://irentstuff.app/'

    - name: Upload ZAP Scan Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap-reports/*.*
