name: Dynamic Application Security Testing Script

on:
  push:
    branches:
      - master
      
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install OWASP ZAP
      run: |
        wget -q -O - https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions/install-ubuntu.sh | bash -s - -q
        sudo apt-get install -y xvfb
        sudo Xvfb :99 -ac &
        export DISPLAY=:99
        /usr/share/zaproxy/zap.sh -daemon -port 8090 -host 127.0.0.1 -config api.key=4sgv6ekunoepofqiof59tqbohr > zap.log 2>&1 &
        sleep 60  

    - name: Install ZAP CLI
      run: pip install zapcli
    
    - name: Run OWASP ZAP Scan
      run: | 
        cat zap.log
        zap-cli quick-scan -r -s xss,sqli --spider -o zap-report.html -l High https://irentstuff.app/
