name: OWASP ZAP Full Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Run ZAP Scan Docker Image
        run: |
            docker pull sherminho/zap-custom:latest
            docker run -e TARGET_URL=https://irentstuff.app/ sherminho/zap-custom:latest
           
    # - name: Checkout
    #   uses: actions/checkout@v2
      
    # - name: Run ZAP Scan
    #   uses: zaproxy/action-baseline@v0.4.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     target: 'https://irentstuff.app/'
