name: Unit tests with Django

on: [push, pull_request]

jobs:
  django_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.9

    - name: Install requirements
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        coverage run manage.py test
        coverage report
