name: Static Application Security Testing Script

on: [push, pull_request]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.9

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit with exclusions and path exclusions
      run: bandit -r . -ll -s B105,B106 -x irentstuff/irentstuffapp/tests || true

