name: Static Application Security Testing Script

on: [push, pull_request]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.9

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r .

    - name: Run Bandit excluding low severity issues
      run: bandit -r . --severity high, medium, critical

      
